<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LARUOSJ" failures="2" tests="19" name="Surefire test" time="5.618" errors="0" timestamp="2025-06-22T12:25:54 NPT">
  <testcase classname="Authentication.LogoutTest" name="@BeforeClass LogIn" time="0.442">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;401&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <401>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Authentication.LogoutTest.LogIn(LogoutTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass LogIn -->
  <testcase classname="Authentication.authenticateTest" name="AuthenticateWithInvalidDevice" time="0.515"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticateWithInvalidLocation" time="0.219"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticateWithNoDevice" time="0.34"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticateWithNoLocation" time="0.372"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticateWithNoUserAgent" time="0.313"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticatewithInvalidEmail" time="0.239"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticatewithInvalidPin" time="0.313"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticatewithMissingEmail" time="0.264"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticatewithMissingPin" time="0.576"/>
  <testcase classname="Authentication.authenticateTest" name="AuthenticatewithWrongPin" time="0.201">
    <failure type="java.lang.AssertionError" message="Code does not start with expected prefix expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Code does not start with expected prefix expected [true] but found [false]
at Authentication.authenticateTest.AuthenticatewithWrongPin(authenticateTest.java:349)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- AuthenticatewithWrongPin -->
  <testcase classname="Authentication.authenticatevalidTest" name="authenticatewithValidCredentials" time="1.743">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;401&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <401>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Authentication.authenticatevalidTest.authenticatewithValidCredentials(authenticatevalidTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- authenticatewithValidCredentials -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithInvalidAuth" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithInvalidAuth -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithInvalidDevice" time="0.001">
    <skipped/>
  </testcase> <!-- logoutwithInvalidDevice -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithInvalidLocation" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithInvalidLocation -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithInvalidUserAgent" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithInvalidUserAgent -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithValidCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithValidCredentials -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithoutAuth" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithoutAuth -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithoutDevice" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithoutDevice -->
  <testcase classname="Authentication.LogoutTest" name="logoutwithoutLocation" time="0.0">
    <skipped/>
  </testcase> <!-- logoutwithoutLocation -->
</testsuite> <!-- Surefire test -->
